apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: carrefour
  labels:
    name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rof20004/carrefour-backend:latest
          ports:
            - containerPort: 8080
