apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: carrefour
  labels:
    name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80