apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: carrefour
  labels:
    name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rof20004/carrefour-frontend:latest
          ports:
            - containerPort: 80
